/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 70938f9e-3e99-4b5b-94a8-c5208c8431e9

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

#check Turing.Dir

/-
Definitions of Turing Machine, Configuration, Step, Reachability, Acceptance (N and co-N), and Space Boundedness.
-/
inductive Move
| Left
| Stay
| Right
deriving DecidableEq, Repr

def Move.toInt : Move → Int
| Move.Left => -1
| Move.Stay => 0
| Move.Right => 1

structure TuringMachine (k : ℕ) (σ : Type) where
  V : Type
  [decV : DecidableEq V]
  [fintypeV : Fintype V]
  edges : Set (V × V × (Fin k → σ) × (Fin (k-1) → σ) × (Fin k → Move))
  startState : V
  acceptState : V
  rejectState : V

structure Configuration (k : ℕ) (σ : Type) (V : Type) where
  state : V
  tapes : Fin k → ℕ → σ
  positions : Fin k → ℤ

variable {k : ℕ} {σ : Type} [DecidableEq σ] [Inhabited σ] [NeZero k]

def step (M : TuringMachine k σ) (c : Configuration k σ M.V) (c' : Configuration k σ M.V) : Prop :=
  ∃ (r : Fin k → σ) (w : Fin (k-1) → σ) (m : Fin k → Move),
    (c.state, c'.state, r, w, m) ∈ M.edges ∧
    (∀ i, c.tapes i (c.positions i).toNat = r i) ∧
    (∀ i : Fin (k-1),
      let idx : Fin k := ⟨i.val + 1, by
        grind⟩
      c'.tapes idx (c.positions idx).toNat = w i) ∧
    (∀ i : Fin k, ∀ n, n ≠ (c.positions i).toNat → c'.tapes i n = c.tapes i n) ∧
    (∀ i, c'.positions i = c.positions i + (m i).toInt) ∧
    (∀ n, c'.tapes 0 n = c.tapes 0 n)

def Reachable (M : TuringMachine k σ) (c1 c2 : Configuration k σ M.V) : Prop :=
  Relation.ReflTransGen (step M) c1 c2

def InitialConfig (M : TuringMachine k σ) (input : List σ) : Configuration k σ M.V :=
  { state := M.startState,
    tapes := fun i n =>
      if i = 0 then
        if n < input.length then input.get! n else default
      else default,
    positions := fun _ => 0 }

def AcceptsN (M : TuringMachine k σ) (input : List σ) : Prop :=
  ∃ c, Reachable M (InitialConfig M input) c ∧ c.state = M.acceptState

def Terminal (M : TuringMachine k σ) (c : Configuration k σ M.V) : Prop :=
  ¬∃ c', step M c c'

def AcceptsCoN (M : TuringMachine k σ) (input : List σ) : Prop :=
  ∀ c, Reachable M (InitialConfig M input) c → Terminal M c → c.state = M.acceptState

def SpaceBounded (M : TuringMachine k σ) (S : ℕ → ℕ) : Prop :=
  ∀ input, ∀ c, Reachable M (InitialConfig M input) c →
    ∀ i, (c.positions i).natAbs ≤ S input.length

#check Nat.log2

/-
Definitions for reachability within n steps and the count of such reachable configurations.
-/
def ReachableInAtMost (M : TuringMachine k σ) (c1 c2 : Configuration k σ M.V) (n : ℕ) : Prop :=
  ∃ path : List (Configuration k σ M.V),
    path.length ≤ n + 1 ∧
    path.head? = some c1 ∧
    path.getLast? = some c2 ∧
    path.Chain' (step M)

def ReachableCount (M : TuringMachine k σ) (input : List σ) (n : ℕ) : ℕ :=
  Nat.card { c : Configuration k σ M.V | ReachableInAtMost M (InitialConfig M input) c n }

/-
Lemma: The set of tapes with content bounded by S is finite.
-/
lemma FiniteBoundedTape {σ : Type} [Fintype σ] [Inhabited σ] [DecidableEq σ] (S : ℕ) :
  Set.Finite { t : ℕ → σ | ∀ n, n > S → t n = default } := by
    -- The set of functions `t : ℕ → σ` such that `t n = default` for all `n > S` is in one-to-one correspondence with the set of functions `Fin (S + 1) → σ`.
    have h_bij : {t : ℕ → σ | ∀ n > S, t n = Inhabited.default} = Set.image (fun f : Fin (S + 1) → σ => fun n => if h : n < S + 1 then f ⟨n, h⟩ else Inhabited.default) (Set.univ : Set (Fin (S + 1) → σ)) := by
      ext t;
      constructor;
      · intro ht;
        use fun i => t i;
        grind;
      · grind;
    exact h_bij ▸ Set.toFinite _

/-
Definition of a bounded configuration, where positions are within [-S, S] and tape contents are default outside [0, S] (except for the read-only tape).
-/
def BoundedConfig (M : TuringMachine k σ) (S : ℕ) (input : List σ) (c : Configuration k σ M.V) : Prop :=
  (∀ i, (c.positions i).natAbs ≤ S) ∧
  (∀ n, c.tapes 0 n = if n < input.length then input.get! n else default) ∧
  (∀ i : Fin k, i.val ≠ 0 → ∀ n, n > S → c.tapes i n = default)

/-
Definition of BoundedTapes: tape 0 matches input, other tapes are default outside [0, S].
-/
def BoundedTapes (k : ℕ) [NeZero k] (σ : Type) [Inhabited σ] (S : ℕ) (input : List σ) (ts : Fin k → ℕ → σ) : Prop :=
  (∀ n, ts 0 n = if n < input.length then input.get! n else default) ∧
  (∀ i : Fin k, i.val ≠ 0 → ∀ n, n > S → ts i n = default)

/-
Lemma: The set of bounded tapes is finite.
-/
lemma FiniteBoundedTapes (k : ℕ) (σ : Type) [Fintype σ] [Inhabited σ] [DecidableEq σ] [NeZero k] (S : ℕ) (input : List σ) :
  Set.Finite { ts | BoundedTapes k σ S input ts } := by
    -- By definition of bounded tapes, the set of bounded tapes is isomorphic to a product of finite sets.
    have h_finite_product : {ts : Fin k → ℕ → σ | BoundedTapes k σ S input ts} ⊆ (Set.pi Set.univ fun i : Fin k =>
      if i.val = 0 then
        Set.image (fun t : Fin input.length → σ => fun n => if h : n < input.length then t ⟨n, h⟩ else default) (Set.univ : Set (Fin input.length → σ))
      else
        Set.image (fun t : Fin (S + 1) → σ => fun n => if h : n ≤ S then t ⟨n, by
          exact?⟩ else default) (Set.univ : Set (Fin (S + 1) → σ))) := by
          intro ts hts; simp_all +decide [ BoundedTapes ];
          intro i; split_ifs <;> simp_all +decide [ Set.mem_range ] ;
          · exact ⟨ fun ⟨ n, hn ⟩ => input[n]?.getD Inhabited.default, funext fun n => by aesop ⟩;
          · use fun n => ts i n;
            ext n; aesop;
    exact Set.Finite.subset ( Set.Finite.pi fun i => by split_ifs <;> [ exact Set.toFinite _ ; exact Set.toFinite _ ] ) h_finite_product

/-
Definition of BoundedPositions and lemma stating it is a finite set.
-/
def BoundedPositions (k : ℕ) (S : ℕ) (ps : Fin k → ℤ) : Prop :=
  ∀ i, (ps i).natAbs ≤ S

lemma FiniteBoundedPositions (k : ℕ) (S : ℕ) :
  Set.Finite { ps | BoundedPositions k S ps } := by
    -- Since each individual set is finite, their product is also finite.
    have h_finite : ∀ i : Fin k, Set.Finite {ps_i : ℤ | ps_i.natAbs ≤ S} := by
      exact fun i => Set.Finite.subset ( Set.finite_Icc ( -S : ℤ ) S ) fun x hx => ⟨ by cases abs_cases x <;> linarith [ hx.out ], by cases abs_cases x <;> linarith [ hx.out ] ⟩;
    exact Set.Finite.subset ( Set.Finite.pi fun i => h_finite i ) ( fun ps hps => by aesop )

/-
Definition of BoundedConfigTuples as the product of states, bounded tapes, and bounded positions.
-/
def BoundedConfigTuples (M : TuringMachine k σ) (S : ℕ) (input : List σ) : Set (M.V × (Fin k → ℕ → σ) × (Fin k → ℤ)) :=
  Set.univ ×ˢ ({ ts | BoundedTapes k σ S input ts } ×ˢ { ps | BoundedPositions k S ps })

/-
Lemma: The set of states is finite.
-/
lemma FiniteStates (M : TuringMachine k σ) : Set.Finite (Set.univ : Set M.V) := by
  -- Since the set of states is finite, its cardinality is a natural number.
  have h_card : Finite (Set.univ : Set M.V) := by
    have h_fintype : Fintype M.V := by
      exact M.fintypeV
    exact Set.finite_univ;
  exact h_card